In [2]:
import math
import numpy as np

In [1]:
import statistics

## Average and Standard Deviation

In [4]:
data1 = [-0.3,0.2,-0.1,0.4,-0.2,-0.3]             #array of data given
x_mean = statistics.mean(data1)                   #using inbuilt function to calculate mean from statistics
print('x average = ', x_mean)                     #print value calculated for mean

x_stdev = statistics.stdev(data1)                 #using inbuilt function to calculate standard deviation from statistics
print('x standard deviation = ', x_stdev)         #print value calculated for mean

x average =  -0.049999999999999996
x standard deviation =  0.28809720581775866


In [5]:
data2 = [0.7,0.6,0.6,0.6,0.0,0.4]
y_mean = statistics.mean(data2)
print('y average = ', y_mean)

y_stdev = statistics.stdev(data2)
print('y standard deviation = ', y_stdev)

y average =  0.48333333333333334
y standard deviation =  0.2562550812504342


In [6]:
data3 = [-0.8,-0.5,0.6,0.3,0.3,-0.1]
z_mean = statistics.mean(data3)
print('z average = ', z_mean)

z_stdev = statistics.stdev(data3)
print('z standard deviation = ', z_stdev) #prints standard deviation for 

z average =  -0.03333333333333335
z standard deviation =  0.5354126134736337


## Covariance Matrix

In [7]:
np.cov(data1, data2)                          #using inbuilt function to calculate covariance matrix between x and y

array([[ 0.083     ,  0.023     ],
       [ 0.023     ,  0.06566667]])

In [8]:
np.cov(data1, data3)

array([[ 0.083     ,  0.032     ],
       [ 0.032     ,  0.28666667]])

In [9]:
np.cov(data2, data3)

array([[ 0.06566667, -0.05266667],
       [-0.05266667,  0.28666667]])

## Correlation Matrix

In [10]:
x_var = statistics.variance(data1)
y_var = statistics.variance(data2)
z_var = statistics.variance(data3)

print((0.023)/(x_stdev)*(y_stdev))                        #print factor covariance matrix is scaled by

0.02045791055845319


In [11]:
# do above step individually for each value in correlation matrix except diagonal as theyre all 1

## Spearman Rank Correlation Coefficient

In [12]:
from scipy.stats import spearmanr
spearmanr(data2,data3)

SpearmanrResult(correlation=-0.43122877254358821, pvalue=0.39325211605109922)

## Rotation Angle

In [13]:
#for specific error matrix given in this question
sigma_xx = 1.0
sigma_yy = 0.8
sigma_xy = 0.1

theta = 0.5 * np.arctan((2 * sigma_xy) / ((sigma_xx)**2)*((sigma_yy)**2))
print('theta = ', theta)

theta =  0.0636538709354


In [14]:
(0.76-1)/0.1

-2.4